/// maincategory

export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY";
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED";
export const GET_MAINCATEGORY = "GET_MAINCATEGORY";
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED";
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY";
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED";
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY";
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED";


/// Subcategory
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const CREATE_SUBCATEGORY_RED = "CREATE_SUBCATEGORY_RED";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED";
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";
export const UPDATE_SUBCATEGORY_RED = "UPDATE_SUBCATEGORY_RED";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const DELETE_SUBCATEGORY_RED = "DELETE_MAINCATEGORY_RED";


/// BRAND
export const CREATE_BRAND = "CREATE_BRAND";
export const CREATE_BRAND_RED = "CREATE_BRAND_RED";
export const GET_BRAND = "GET_BRAND";
export const GET_BRAND_RED = "GET_BRAND_RED";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_BRAND_RED = "UPDATE_BRAND_RED";
export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_BRAND_RED = "DELETE_BRAND_RED";


/// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_RED = "GET_PRODUCT_RED";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED";


/// Testimonial
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

